# Generated by Django 5.1.1 on 2024-10-12 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapterimagesitem',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.comic'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_comic', to='apps.comic'),
        ),
        migrations.AddField(
            model_name='comicimagesitem',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.comic'),
        ),
        migrations.AddField(
            model_name='comicimagesitem',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.comicimage'),
        ),
        migrations.AddField(
            model_name='comic',
            name='images',
            field=models.ManyToManyField(related_name='pictures', through='apps.ComicImagesItem', to='apps.comicimage'),
        ),
        migrations.AddField(
            model_name='comment',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_chapter', to='apps.chapter'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comic',
            name='genres',
            field=models.ManyToManyField(blank=True, to='apps.genre'),
        ),
        migrations.AddField(
            model_name='comic',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic_type', to='apps.type'),
        ),
        migrations.AddField(
            model_name='usersitem',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.comic'),
        ),
        migrations.AddField(
            model_name='usersitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comic',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='comics', through='apps.UsersItem', to=settings.AUTH_USER_MODEL),
        ),
    ]
