# Generated by Django 5.1.1 on 2024-10-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='downloaded_at',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='downloaded_at',
        ),
    ]
