# Generated by Django 5.1.1 on 2024-10-12 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_chapter_downloaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterimagesitem',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_photo', to='apps.chapterimage'),
        ),
        migrations.AlterField(
            model_name='comicimagesitem',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic_photo', to='apps.comicimage'),
        ),
    ]
